libertydata <- read.csv("/Users/janardhanbonu/OneDrive/MUM/datamining/libertystore/LibertyStoreDecisionTree.csv")
library("RWeka", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
library("RWekajars", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
library(RWeka)
libertytree <- J48(decision., data=libertydata)
libertytree <- J48(libertydata$decision., data=libertydata)
attach(libertydata)
libertytree <- J48(libertydata$decision., data=libertydata)
libertytree <- J48(libertydata$decision~., data=libertydata)
plot(libertytree)
libertytree <- J48(decision~., data=libertydata)
libertytree <- J48(decision~citysize+aviincome+localinvestors+lohasawareness, data=libertydata)
plot(libertytree)
libertytree
summary(libertytree)
m1 <- J48(Species ~ ., data = iris)
summary(m1)
table(iris$Species, predict(m1))
if(require("party", quietly = TRUE)) plot(m1)
write_to_dot(m1)
library("Rgraphviz")
ff <- tempfile()
write_to_dot(m1, ff)
plot(agread(ff))
DF2 <- read.arff(system.file("arff", "contact-lenses.arff", package = "RWeka"))
m2 <- J48(`contact-lenses` ~ ., data = DF2)
table(DF2$`contact-lenses`, predict(m2))
if(require("party", quietly = TRUE)) plot(m2)
DF3 <- read.arff(system.file("arff", "cpu.arff", package = "RWeka"))
m3 <- M5P(class ~ ., data = DF3)
if(require("party", quietly = TRUE)) plot(m3)
DF4 <- read.arff(system.file("arff", "weather.arff", package = "RWeka"))
m4 <- LMT(play ~ ., data = DF4)
table(DF4$play, predict(m4))
if(require("mlbench", quietly = TRUE) && require("party", quietly = TRUE)) {
data("PimaIndiansDiabetes", package = "mlbench")
m5 <- J48(diabetes ~ ., data = PimaIndiansDiabetes, control = Weka_control(R = TRUE))
plot(m5)
}
m4
plot(libertytree)
plot(libertytree, simple=t)
plot(libertytree, simple=T)
plot(libertytree, simple=TRUE)
plot(libertytree, simple=TRUE)
DF2 <- read.arff(system.file("arff", "contact-lenses.arff", package = "RWeka"))
m2 <- J48(`contact-lenses` ~ ., data = DF2)
tree(m2)
plot(m2)
table(DF2$`contact-lenses`, predict(m2))
table(libertydata$decision, predict(libertytree))
plot(libertytree)
install.packages("C50")
library(C50)
libertydata <- read.csv("/Users/janardhanbonu/OneDrive/MUM/datamining/LibertyStoreDecisionTree.csv")
source('~/OneDrive/MUM/datamining/DivvyDataFinal.R')
libertyc50tree <- C50(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data="libertydata")
detach("package:C50", unload=TRUE)
library("C50", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data="libertydata")
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata)
plot(libertyc50tree)
libertyPredict <- read.csv("/Users/janardhanbonu/OneDrive/MUM/datamining/LibertyStorePredict.csv")
predict(libertyc50tree, libertyPredict$Decision)
predict(libertyc50tree, libertyPredict)
summary(libertyc50tree)
install.packages(c("car", "gvlma", "MASS", "leaps"))
install.packages(c("car", "gvlma", "MASS", "leaps"))
libertydata <- read.csv("/Users/janardhanbonu/OneDrive/MUM/datamining/LibertyStoreDecisionTree.csv")
libertyc50tree <- C50(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data="libertydata", control = C5.0Control(winnow = TRUE))
library("C50", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
libertyc50tree <- C50(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data="libertydata", control = C5.0Control(winnow = TRUE))
library(C50)
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data="libertydata", control = C5.0Control(winnow = TRUE))
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data="libertydata", control = C5.0Control(winnow = TRUE))
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata)
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control = C5.0Control(winnow = TRUE))
plot(libertyc50tree)
C5imp(libertyc50tree, metric = "splits")
C5imp(libertyc50tree)
plot(libertyc50tree,trail=NULL)
plot(libertyc50tree,trail=NULL, subtree=NULL)
plot(libertyc50tree,trail=NULL, subtree=NULL)
plot(libertyc50tree,trail=NULL, subtree=NULL, col="red")
plot(libertyc50tree, pmean, col="red")
plot(libertyc50tree$Decision, pmean, col="red")
plot(libertyc50tree, col="red")
plot(libertyc50tree, type="simple")
plot(libertyc50tree, terminal_panel = node_density)
plot(libertyc50tree, type = c("extended", "simple"))
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, tp_args = list(),
     inner_panel = node_inner, ip_args = list(),
     edge_panel = edge_simple, ep_args = list(),
     drop_terminal = (type[1] == "extended"),
     tnex = (type[1] == "extended") + 1, newpage = TRUE)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = (type[1] == "extended"))
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1,inner_panel = node_barplot)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=3)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=2)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=1)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=0)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=1)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, trail=1)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, trail=2)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, trail=3)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, trail=4)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree4)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=4)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=3)
plot(libertyc50tree, type = c("extended", "simple"), terminal_panel = NULL, drop_terminal = TRUE, tnex=1, subtree=1)
library(rpart.plot)
rpart.plot(tree1)
install.packages("rpart")
install.packages("rpart.plot")
library(rpart)
library(rpart.plot)
rpart.plot(libertyc50tree)
C5.0Control(subset = TRUE,
            bands = 0,
            winnow = FALSE,
            noGlobalPruning = FALSE,
            CF = 0.25,
            minCases = 2,
            fuzzyThreshold = FALSE,
            sample = 0,
            seed = sample.int(4096, size = 1) - 1L,
            earlyStopping = TRUE,
            label = "outcome")
C5.0Control(subset = TRUE)
C5.0Control(subset = TRUE, bands = 0, winnow = FALSE, noGlobalPruning = FALSE, CF = 0.25, minCases = 2,fuzzyThreshold = FALSE,sample = 0,seed = sample.int(4096, size = 1) - 1L, earlyStopping = TRUE,label = "outcome")
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control())
plot(libertyc50tree)
C5.0Control(subset = TRUE, bands = 0, winnow = FALSE, noGlobalPruning = TRUE, CF = 0.25, minCases = 2,fuzzyThreshold = FALSE,sample = 0,seed = sample.int(4096, size = 1) - 1L, earlyStopping = TRUE,label = "outcome")
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control())
plot(libertyc50tree)
C5.0Control(subset = TRUE, bands = 0, winnow = FALSE, noGlobalPruning = TRUE, CF = 0.25, minCases = 2,fuzzyThreshold = FALSE,sample = 0,seed = sample.int(4096, size = 1) - 1L, earlyStopping = FALSE,label = "outcome")
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control())
plot(libertyc50tree)
C5.0Control(subset = TRUE, bands = 0, winnow = FALSE, noGlobalPruning = TRUE, CF = 0.25, minCases = 3,fuzzyThreshold = FALSE,sample = 0,seed = sample.int(4096, size = 1) - 1L, earlyStopping = FALSE,label = "outcome")
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control())
plot(libertyc50tree)
C5.0 -f libertydata
c5.0 -f libertydata
c5.0 -f libertyc50tree
c5.0
c50
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control(CF=1))
plot(libertyc50tree)
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control(CF=2))
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control(CF=0.5))
plot(libertyc50tree)
libertyc50tree <- C5.0(Decision~CitySize+AvgIncome+LocalInvestors+LOHASAwareness,data=libertydata, control=C5.0Control(CF=1))
plot(libertyc50tree)
summary(libertytree)
summary(libertyc50tree)
